services:
  nzbwebdav:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
    environment:
      # Enable rclone NFS
      - NFS_ENABLED=true
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=info
    volumes:
      - /root/nzbdav:/config
      - /data/streaming:/data/streaming

  nfs_server:
    image: erichough/nfs-server:latest
    ports:
      - "2049:2049"
    environment:
      - NFS_EXPORT_0='/nzbdav 192.168.10.0/24(rw,no_subtree_check)'
    volumes:
      - streaming_media:/nzbdav
    cap_add:
      - SYS_ADMIN
    depends_on:
      - nzbwebdav

# note: use_cookies, buffer_size, and links need to be added in the rclone config
# file /var/lib/docker-plugins/rclone/config/rclone.conf, like:
# [nzbdav]
# type = webdav
# url = http://localhost:8080
# vendor = other
# user = ...
# pass = ...
# override.use_cookies = true
# override.links = true
# override.buffer_size = 1024
volumes:
  streaming_media:
    driver: rclone
    driver_opts:
      remote: "nzbdav:"
      allow_other: "true"
      vfs_cache_mode: full
      dir_cache_time: 1s
      vfs_cache_max_size: 5G
      vfs_cache_max_age: 180m
      uid: 1000
      gid: 1000
