services:
  nzbwebdav:
    build: .
    ports:
      - "3000:3000"
      - "8080:8080"
      - "2049:2049" # rclone NFS server
    environment:
      # Enable rclone NFS
      - NFS_ENABLED=true
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
    volumes:
      - /root/nzbdav:/config
      - /data/streaming:/data/streaming
